### ISSUE TITLE
Unable to retrieve camera credentials from SecretProvider at path 'credentials001': No value for the keys: [mode] exists. Retrying for 11.859810351s

### ISSUE THREAD

**Issue by wangyongxiao** [edgexfoundry-holding/device-onvif-camera#101]
i follow getting-started-with-docker-security.md, getting-started-with-docker.md, Run device-onvif-camera with edgex-compose to config device-onvif-camera，the auto discovery can work, but the log has the warn info below

> Unable to retrieve camera credentials from SecretProvider at path 'credentials001': No value for the keys: [mode] exists. Retrying for 11.859810351s

i has do secret, like this, the return  code is 201 that i think is success, so what can i do now

> root@xinyustorage:~# curl --request POST 'http://localhost:59984/api/v2/secret' --header 'Content-Type: application/json' --data-raw '{
    "apiVersion":"v2",
    "path": "credentials001",
    "secretData":[
        {
            "key":"username",
            "value":"admin"
        },
        {
            "key":"password",
            "value":"Admin12345"
        }
    ]
}'
{"apiVersion":"v2","statusCode":201}

**Comment by wangyongxiao** [comment]
and i also   try SECRETSTORE_SECRETSFILE environment variable to add credentials001 according to
[Seeding Service Secrets](https://docs.edgexfoundry.org/2.2/security/SeedingServiceSecrets/)
but it can't work either

**Comment by ajcasagrande** [comment]
You need to add the mode in the secret value, like so:

```
curl --request POST 'http://localhost:59984/api/v2/secret' \
--header 'Content-Type: application/json' \
--data-raw '{
    "apiVersion":"v2",
    "path": "credentials001",
    "secretData":[
        {
            "key":"username",
            "value":"admin"
        },
        {
            "key":"password",
            "value":"Admin12345"
        },
        {
            "key":"mode",
            "value":"usernametoken"
        }
    ]
}'
```

**Comment by wangyongxiao** [comment]
thanks，it work
and the relevant instructions in the [getting-started-with-docker-security.md](https://github.com/edgexfoundry/device-onvif-camera/blob/main/doc/getting-started-with-docker-security.md#4-add-the-username-and-password-for-the-onvif-camera) need to be modified
it's no "mode" here
