### ISSUE TITLE
Run Security Mode instructions In device-onvif-camera/doc/docker-compose/read.md 

### ISSUE THREAD

**Issue by wangyongxiao** [edgexfoundry-holding/device-onvif-camera#102]
[here](https://github.com/edgexfoundry/device-onvif-camera/tree/main/doc/docker-compose#run-security-mode) 
in device-onvif-camera/doc/docker-compose/read.md 
at the section Run Security Mode
>Enter the command make gen ds-onvif-camera to generate non-secure compose file
should be 
Enter the command make gen ds-onvif-camera to generate  compose file

the "non-secure " should be delete

**Comment by lenny-goodell** [comment]
This README is being removed in this PR 
https://github.com/edgexfoundry/device-onvif-camera/pull/95
