### ISSUE TITLE
Missing device service API specification

### ISSUE THREAD

**Issue by farshidtz** [edgexfoundry-holding/device-onvif-camera#106]
# 📚 Docs or Wiki Bug Report

### Description [**REQUIRED**]

The API of the device service translates REST/HTTP requests to SOAP/HTTP. The [onvif features](https://github.com/edgexfoundry/device-onvif-camera#onvif-features) section of README links to ONVIF specs which document the SOAP API.
Things are straight forward when it comes to GET commands. However, it isn't that easy to figure out the data model of the input.
The only documented example of a SET command is in [docs/getting-started-guide](https://github.com/edgexfoundry/device-onvif-camera/blob/e5053f8c731e365d1df3f2055d168c1a15fdfcf5/doc/getting-started-guide.md#8-execute-a-set-command---write-multiple-resource).

It took me some time to figure out how to do a [RelativeMove](https://github.com/edgexfoundry/device-onvif-camera/blob/e5053f8c731e365d1df3f2055d168c1a15fdfcf5/cmd/res/profiles/camera.yaml#L391). This only became obvious after I accidentally discovered the device-onvif-camera's [Postman collection](https://github.com/edgexfoundry/device-onvif-camera/blob/e5053f8c731e365d1df3f2055d168c1a15fdfcf5/doc/postman/device-onvif-camera.postman_collection.json). It would be nice to make that more accessible. I could use that to figure out how to do RelativeMove:
```
curl -X PUT http://0.0.0.0:59882/api/v2/device/name/tp-link-Tapo-C210-3fa1fe68-b915-4053-a3e1-14ebb69b5003/RelativeMove -H 'Content-Type: application/json' \
    -d '{"RelativeMove": {"ProfileToken": "profile_1","Translation": {"PanTilt": {"x": 50,"y": 50}}}}'
``` 
which isn't obvious by just looking at the onvif spec:
![image](https://user-images.githubusercontent.com/11150423/178546398-a7fdd86c-9c95-458b-98cc-1a6c20bd6196.png)

I think instead of the Postman collection, the service should publish the spec based on the default [camera.yaml](https://github.com/edgexfoundry/device-onvif-camera/blob/main/cmd/res/profiles/camera.yaml) profile using OpenAPI spec, added to the docs with Swagger UI.

### What's the affected URL? [**REQUIRED**]
https://github.com/edgexfoundry/device-onvif-camera/tree/main/doc

### Expected vs Actual Behavior
API specification is not available.

**Comment by ajcasagrande** [comment]
Related: https://github.com/edgexfoundry/device-sdk-go/issues/1165
