### ISSUE TITLE
Unable to configure and launch device-onvif-camera

### ISSUE THREAD

**Issue by sagark82** [edgexfoundry-holding/device-onvif-camera#107]
Hello

I am trying to setup a video streaming from my mobile to edgex. Following steps have been followed: -
1. Installed IP Camera app on my android mobile
2. Included device-onvif container in my docker-compose
3. Tried to configure device and profile by changing relevant parameters  
4. device address and port = ip and port displayed on mobile by IP Phone app
5. EndpointRefAddress = my laptop wifi ip address 
6. BaseNotificationURL = ip and port displayed on mobile by IP Phone app
7. [AppCustom.CredentialsMap]
  credentials001 = MAC address of my mobile
8. Updated Generic-Onvif-Provision-Watcher.json. identifier address  = ip and port displayed on mobile by IP Phone app
9. Added 3 parameters in docker-compose - DEVICE_DEVICESDIR: /custom-config/devices
      DEVICE_PROFILESDIR: /custom-config/profiles
      DEVICE_PROVISIONWATCHERDIR: /custom-config/provision_watchers (not sure about this one, how can we override provision watcher location??)

Attaching config files for reference as well as error log from docker desktop. Any help to resolve this will be highly appreciated. Thanks in advance.
[config and log.zip](https://github.com/edgexfoundry/device-onvif-camera/files/9109917/config.and.log.zip)

**Comment by ajcasagrande** [comment]
Hi,

Can you send a link to the exact app you are trying to use? Does it claim to be Onvif compliant?

A few clarifications on your configuration:

3. Your `camera.toml` file looks exactly like a `configuration.toml` file. You only need to include the `[[DeviceList]]` section

5. `EndpointRefAddress` is generally a UUID that is defined by the camera. For now, I would leave that field out.

6. You actually want this to match the IP address and Port of the machine running docker, making sure the device service is port forwarded to be more open than just `127.0.0.1`. This is only used for subscribing to camera events.

7. This feature is not used in the current build, it is WIP. When the feature is finished you seem to have done it correctly assuming that is what the app would respond to as the MAC (though looking at the logs it appears that app does not support retrieving the MAC). If `credentials001` is set as the default secret path, defining MACs in that group is optional (they will get assigned it anyways).

8. A few things here. What you did is not needed for typical use cases. It is for discovery only and what you have done is basically created an allow list with a single device in it, blocking all others (from being provisined after being discovered). Also, the `Address` should be just the IP and you would add a field for `Port` to put the port number.

9. Provision watcher directory is not an EdgeX supported feature yet, so you configure it via the app custom config: `APPCUSTOM_PROVISIONWATCHERDIR`


Overall it seemed like it worked, but didn't work. As in, it appeared like the device service could connect to it, but not really many commands were supported.

**Comment by sagark82** [comment]
@ajcasagrande , Thanks for the reply. I will make changes as suggested
1. I am using https://play.google.com/store/apps/details?id=com.pas.webcam&hl=en_IN&gl=US app. This seems to the most popular app to convert mobile to IP cam.
2. Also, by using MACAddress attribute in DeviceList.Protocols.Onvif in camera.toml the error of mac not found is gone. I am now able to run many commands e.g. snapshot, devicedetails which are running fine.
3. However, not able to run StreamURI. It keeps failing with following error
**{"apiVersion":"v2","message":"request failed, status code: 500, err: {\"apiVersion\":\"v2\",\"message\":\"error reading DeviceResourece StreamUri for Camera001 -\\u003e failed to execute read command -\\u003e invalid request for the function 'GetStreamUri' of web service 'Media'. Onvif error: fault reason: End at NUL buffer input: message transfer interrupted, fault detail: , fault code: SOAP-ENV:Sender  \",\"statusCode\":500}","statusCode":500}**  
4. I am sure the problem is with the parameter {{EDGEX_MEDIA_PROFILE_BASE64}} which is to be passed in the command. Any suggestions on how to populate this parameter. Attaching the output of GetProfiles command which runs successfully.
[GetProfiles.txt](https://github.com/edgexfoundry/device-onvif-camera/files/9114264/GetProfiles.txt)

**Comment by ajcasagrande** [comment]
@sagark82 Thanks for the link. Based on your `GetProfiles.txt` it seems like many different profiles are supported.

```shell
jq '.event.readings[0].objectValue.Profiles[].Token' < GetProfiles.txt
```

```
h264_ulaw_1920x1080
jpeg_ulaw_1920x1080
novideo_ulaw_1920x1080
h264_opus_1920x1080
jpeg_opus_1920x1080
novideo_opus_1920x1080
h264_noaudio_1920x1080
jpeg_noaudio_1920x1080
```

Do keep in mind that whatever URI is returned from the service is currently not authenticated, so if the ip camera app requires authentication for the stream, you would add it via basic auth: `rtsp://<user>:<password>@<ip-address>:<port>`

**Comment by sagark82** [comment]
@ajcasagrande , thanks its working now!!!
