### ISSUE TITLE
Delay in obtaining DeviceStatus for pre-defined and manually added devices

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry-holding/device-onvif-camera#121]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
device-onvif-camera

### Is this a regression?
No

### Description and Minimal Reproduction [**REQUIRED**]
When a device is added either via pre-defined devices in `camera.toml`, or via the core-metadata REST API, the device will lack a `DeviceStatus` until the next time the `checkStatuses` job is run.

In the case of pre-defined devices (using default configuration) this can be up to 45 seconds after service startup. In the case of REST API, it can be up to 30 seconds.

## 🌍  Your Environment
**Deployment Environment:**
Docker + EdgeX-Compose

**EdgeX Version [**REQUIRED**]:**
2.2

**Anything else relevant?**

**Comment by vchitike** [comment]
Verified that retrieving device status not taking 30 seconds or 45 seconds longer with images on 10/28/22.
Tested with predefined devices in configuraiton.toml file and adding devices manually with curl command. In both cases, noticed that device status called within 1 or 2 secs after services are up or after adding device manually with curl command.
