### ISSUE TITLE
Hikvision-DS-2DE2A404IW-DE3- Get device service capabilities API gives an error 

### ISSUE THREAD

**Issue by vyshali-chitikeshi** [edgexfoundry-holding/device-onvif-camera#212]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
Onvif service

### Is this a regression?
No

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]

Device service capabilities API gives an error
## 🔥 Exception or Error
<pre><code>

{
    "apiVersion": "v2",
    "message":"request failed, status code: 500, err: {\"apiVersion\":\"v2\",\"message\":\"error reading DeviceResourece DeviceCapabilities for HIKVISION-DS-2DE2A404IW-DE3-099f4000-4d50-11b4-82c8-c06ded544d95 -\> failed to execute read command -\> failed to create 'GetServiceCapabilities' response for the web service 'Device' -\> cannot unmarshal into device.EAPMethodTypes\",\"statusCode\":500}",
    "statusCode": 500
}
![Screenshot from 2023-01-13 00-53-33](https://user-images.githubusercontent.com/60447543/212268205-5dd016bc-083c-4107-9286-c1a9ef58efeb.png)

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by vchitike** [comment]
![Screenshot from 2023-01-13 00-53-33](https://user-images.githubusercontent.com/60447543/212269842-d8ab39e2-0362-4d8d-8428-7281503365e4.png)

**Comment by ajcasagrande** [comment]
Looks like an issue with the internal onvif library

**Comment by lenny-goodell** [comment]
@ajcasagrande , bumped it to a Medium. Can you please submit bug against the IOTech package and link it here?

**Comment by vchitike** [comment]
It works correctly with latest V3 code, find attached.
Closing this defect
![Screenshot from 2023-06-06 23-14-00](https://github.com/edgexfoundry/device-onvif-camera/assets/60447543/06b7edd7-a396-461b-8095-d143a2b3da22)
