### ISSUE TITLE
Hikvision-DS-2DE2A404IW-DE3- Set scopes API gives an error

### ISSUE THREAD

**Issue by vyshali-chitikeshi** [edgexfoundry-holding/device-onvif-camera#213]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 

Onvif service
### Is this a regression?
No

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]
Set scopes API supposed to update all configurable scopes with desired scope item, however it throws an error. API command and output attached.

## 🔥 Exception or Error
<pre><code>

{
    "apiVersion": "v2",
    "message":"request failed, status code: 500, err: {\"apiVersion\":\"v2\",\"message\":\"error writing DeviceResourece Scopes for HIKVISION-DS-2DE2A404IW-DE3-099f4000-4d50-11b4-82c8-c06ded544d95 -\> failed to execute write command, \<nil\> -\> failed to execute the request for the function 'SetScopes' of web service 'Device'. Onvif error: fault reason: the parameter value is illegal, fault detail: User NULL, fault code: env:Sender ter:InvalidArgVal ter:InvalidParameter\",\"statusCode\":500}",
    "statusCode": 500
}
![Screenshot from 2023-01-13 01-01-59](https://user-images.githubusercontent.com/60447543/212269610-5e35b06f-8256-47fc-b49f-1f9ee85997c4.png)

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by vchitike** [comment]
![Screenshot from 2023-01-13 01-01-59](https://user-images.githubusercontent.com/60447543/212269720-e8b4b921-3e1f-46be-a15c-a38f1d9ffc64.png)

**Comment by ajcasagrande** [comment]
@vyshali-chitikeshi According to our documentation, the body is supposed to look different than you have it. Try this:

https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/device-onvif-camera/2.3.0#/Auto%20Discovery/put_api_v2_device_name__EDGEX_DEVICE_NAME__Scopes

https://www.onvif.org/ver10/device/wsdl/devicemgmt.wsdl#op.SetScopes

```json
{
  "Scopes": {
    "Scopes": [
      "http//:123"
    ]
  }
}
```


Edit: You have used the schema as for `AddScopes` which is different than this command.

**Comment by vchitike** [comment]
@ajcasagrande Not sure why I used ScopeItem, i think that's  how we have been testing on Tapo as well.
With API body you provided it works correctly on Hikvision camera. Closing this defect .
