### ISSUE TITLE
Bosch camera- Create users not working.

### ISSUE THREAD

**Issue by surajitx-pal** [edgexfoundry-holding/device-onvif-camera#30]
Summary of the problem:
'Create Users' API not creating new user.

Issue reproducible on below camera models:
#Bosch DINION 6000HD

Reproduce steps:

   Execute this command to create a new user (Note : new user only creates through BOSH camera web-page login)

curl -X PUT http://localhost:59882/api/v2/device/name/Bosch-DINION-IP-starlight-6000-HD-00075fd8-7c31-317c-d85f-0700075fd85f/CreateUsers \
    --header 'Content-Type: application/json' \
    --data-raw '
    {
    "CreateUsers": {
        "User": [
            {
                "Username": "Test",
                "Password" : "Tes123456!",
                "UserLevel": "User"
            }
        ]
    }
}'

Expected result: Create users api will creates an user successfully
Actual result:  - fault code: SOAP-ENV:Receiver ter:Action -500 return code.

**Comment by weichou1229** [comment]
@surajitx-pal 
The username is too short, you can test it via the GUI, sometimes the camera didn't return the error message properly, it depends on the implementation of the manufacturer.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/11187505/163583743-a2827438-98aa-4774-9ab1-521ee4520077.png">

**Comment by brianointel** [comment]
verified on the Bosch camera in postman with:

{
    "CreateUsers": {
        "User": [
            {
                "Username": "Test1234",
                "Password" : "Tes123456!",
                "UserLevel": "User"
            }
        ]
    }
}



getUser response:

{
    "apiVersion": "v2",
    "statusCode": 200,
    "event": {
        "apiVersion": "v2",
        "id": "812ef84e-bbf5-4875-9f68-ff8eca2ddfc7",
        "deviceName": "Camera001",
        "profileName": "onvif-camera",
        "sourceName": "Users",
        "origin": 1650651040201501900,
        "readings": [
            {
                "id": "d390b8f7-a909-4734-9dc2-70c15a2dcacf",
                "origin": 1650651040201501900,
                "deviceName": "Camera001",
                "resourceName": "Users",
                "profileName": "onvif-camera",
                "valueType": "Object",
                "objectValue": {
                    "User": [
                        {
                            "UserLevel": "Operator",
                            "Username": "user"
                        },
                        {
                            "UserLevel": "Administrator",
                            "Username": "service"
                        },
                        {
                            "UserLevel": "User",
                            "Username": "live"
                        },
                        {
                            "UserLevel": "User",
                            "Username": "Test1234"
                        }
                    ]
                }
            }
        ]
    }
}

**Comment by vchitike** [comment]
This  issue can be closed

**Comment by weichou1229** [comment]
Issue resolved.
