### ISSUE TITLE
Update security mode documentation - need to provide default command instructions in .env file

### ISSUE THREAD

**Issue by vyshali-chitikeshi** [edgexfoundry-holding/device-onvif-camera#44]
For security mode (using vault), default command needs to be changed in .env file.
DEFAULT_EDGEX_RUN_CMD_PARMS="/device-onvif-camera --registry --confdir=/res"

Need to update documentation to reflect this
https://github.com/edgexfoundry-holding/device-onvif-camera/blob/main/doc/docker-compose/README.md

**Comment by lenny-goodell** [comment]
Closing as the README reference is going to be removed now that EdgeX Compose Builder supports the camera services.
