### ISSUE TITLE
Update security mode documentation- need to change onvif image path

### ISSUE THREAD

**Issue by vyshali-chitikeshi** [edgexfoundry-holding/device-onvif-camera#45]
In security mode documentation, need to change omvif image path.
Documentation URL:  https://github.com/edgexfoundry-holding/device-onvif-camera/blob/main/doc/auto-discovery-docker.md

For security mode, currently it has below
image: edgex/device-onvif-camera${ARCH}:${DEVICE_ONVIFCAM_VERSION}

it should be change to below:
image: edgexfoundry/device-onvif-camera${ARCH}:${DEVICE_ONVIFCAM_VERSION}

**Comment by ajcasagrande** [comment]
Closed as file referenced is no longer present
