### ISSUE TITLE
Add Postman script for test purpose

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry-holding/device-onvif-camera#47]

**Comment by vchitike** [comment]
Do you need postman collection for Bosch camera api testing?

**Comment by weichou1229** [comment]
Yes, I want to add the postman collections for the `device-onvif-camera`  and `Onvif` APIs.
- `device-onvif-camera` APIs are used to test the device service.
- `Onvif` APIs are used to test the camera directly.
