### ISSUE TITLE
Remove Docker Compose folder now that this is in Compose Builder

### ISSUE THREAD

**Issue by lenny-goodell** [edgexfoundry-holding/device-onvif-camera#69]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
doc/docker-compose folder

### Description [**REQUIRED**]
This is no longer needed now that Compose Builder in edgex-compose has been update to included this
Also https://github.com/edgexfoundry/device-onvif-camera/blob/main/doc/auto-discovery-docker.md
needs to be reworked with compose builder in mind. 

### Describe the solution you'd like
remove folder and update main README to describe how to use Compose Builder, including any needed Env Overrides or changes in Consul

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by lenny-goodell** [comment]
@cloudxxx8 , @weichou1229 The Intel team has prioritized the remaining issues. 
Looking to fix all marked as `High` prior to the first release. 
The team would like your help with this one and will handle the remaining Highs. THX!

**Comment by weichou1229** [comment]
No problem, will do.
