### ISSUE TITLE
HIKVISION camera profile

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry-holding/device-onvif-camera#74]
A specific camera profile is referenced for HIKVISION, however that profile does not exist in the profiles directory.

https://github.com/edgexfoundry/device-onvif-camera/blob/main/doc/auto-discovery.md#example---hikvision-onvif-camera-provision

Is this profile still relevant, or should the references be removed?

**Comment by weichou1229** [comment]
Thanks for catching that, we should use the default profile `onvif-camera`.
