### ISSUE TITLE
Can DisconnectDevice be safely removed?

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry-holding/device-onvif-camera#76]
Why does `DisconnectDevice` exist? It does not appear to implement any interface, and it just warns that it is not implemented. Can it be safely removed?

https://github.com/edgexfoundry/device-onvif-camera/blob/ca3b9af0f0e169c629bbfa3887ac93d5f6dd5103/internal/driver/driver.go#L223-L228

**Comment by lenny-goodell** [comment]
Apparently it can be removed.
https://github.com/edgexfoundry/device-sdk-go/commit/706a27ec0b288e96ae2d850b328495468dbc1e63
https://github.com/edgexfoundry/device-sdk-go/pull/290
