### ISSUE TITLE
Need to update onvif image tag in add-device-onvif-camera.yml file

### ISSUE THREAD

**Issue by vyshali-chitikeshi** [edgexfoundry-holding/device-onvif-camera#8]
Need to change onvif image location in add-device-onvif-camera.yml file.

Currently it has below:
device-onvif-camera:
    image: edgex/device-onvif-camera${ARCH}:${DEVICE_ONVIFCAM_VERSION}

It should change to below:
device-onvif-camera:
    image: edgexfoundry/device-onvif-camera${ARCH}:${DEVICE_ONVIFCAM_VERSION}

**Comment by weichou1229** [comment]
@vyshali-chitikeshi 
PR opened https://github.com/edgexfoundry-holding/device-onvif-camera/pull/9, could you help review?
