### ISSUE TITLE
netscan discovery was called, but DiscoverySubnets are empty!

### ISSUE THREAD

**Issue by wangyongxiao** [edgexfoundry-holding/device-onvif-camera#96]
# 📚 Docs or Wiki Bug Report

### Description [**REQUIRED**]

 According to the steps of  
[auto-discovery-docker.md](https://github.com/edgexfoundry/device-onvif-camera/blob/main/doc/auto-discovery-docker.md)  i get an msg below:

`level=WARN ts=2022-07-01T07:46:12.894347595Z app=device-onvif-camera source=driver.go:580 msg="netscan discovery was called, but DiscoverySubnets are empty!"`
 
and i found the DiscoverySubnets is empty  in configration.toml which is in device-onvif-camera container

and i can not change it because it's read_only

what can i do now?

**Comment by weichou1229** [comment]
You should override the settings by env, will update the doc via this PR https://github.com/edgexfoundry/device-onvif-camera/pull/95
`APPCUSTOM_DISCOVERYSUBNETS: "192.168.1.0/24,10.0.0.0/24"`

**Comment by wangyongxiao** [comment]
it work

**Comment by wangyongxiao** [comment]
@weichou1229  can you tell me where  to find APPCUSTOM_DISCOVERYSUBNETS doc?
i can't find it anywhere i konw

**Comment by weichou1229** [comment]
See https://github.com/edgexfoundry/device-onvif-camera/blob/main/cmd/res/configuration.toml#L120 or https://github.com/edgexfoundry/device-onvif-camera/blob/main/doc/auto-discovery.md#usage
