### ISSUE TITLE
“make run device-onvif-camera” should be  “make run -onvif-camera” in auto-discovery-docker.md

### ISSUE THREAD

**Issue by wangyongxiao** [edgexfoundry-holding/device-onvif-camera#97]
# 📚 Docs or Wiki Bug Report

### Description [**REQUIRED**]

 
“make run device-onvif-camera” should be  “make run -onvif-camera” in auto-discovery-docker.md

[at here](https://github.com/edgexfoundry/device-onvif-camera/blob/main/doc/auto-discovery-docker.md#deploy-edgex-services-and-device-onvif-camera)

**Comment by weichou1229** [comment]
will update the doc via this PR https://github.com/edgexfoundry/device-onvif-camera/pull/95
